INSERT INTO PRODUCTS(ID,NAME,EAN) VALUES (null,'SAMSUNG Galaxy S20+ SM-G985 Blue','1234567')
INSERT INTO ORDERS(ID,ILOSC_PRODUKTOW,ADRES_ZAMOWIENIA,KOSZT) VALUES (null, 10,'Poznań',55)
INSERT INTO USERS(ID, NAME, MAIL, SURNAME) VALUES (null, 'Jan', 'Jan24@o2.pl', 'Kowalski')